### ISSUE TITLE
User Routes

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#189]
Some already implemented features have been omitted.

- [ ] [Get User Profile](https://discord-userdoccers.vercel.app/resources/user#get-user-profile) 
- [ ] [Modify User Profile](https://discord-userdoccers.vercel.app/resources/user#modify-user-profile)
- [ ] [Disable User](https://discord-userdoccers.vercel.app/resources/user#disable-user)
- [ ] [Delete User](https://discord-userdoccers.vercel.app/resources/user#disable-user)
- [ ] [Verify Captcha](https://discord-userdoccers.vercel.app/resources/user#verify-user-captcha)
- [ ] [Modify User Email](https://discord-userdoccers.vercel.app/resources/user#modify-user-email)
- [ ] [Verify User Email Change](https://discord-userdoccers.vercel.app/resources/user#verify-user-email-change)
- [ ] [Get Pomelo Suggestions](https://discord-userdoccers.vercel.app/resources/user#get-pomelo-suggestions)
- [ ] [Get Pomelo Eligibility](https://discord-userdoccers.vercel.app/resources/user#get-pomelo-eligibility)
- [ ] [Create Pomelo Migration](https://discord-userdoccers.vercel.app/resources/user#create-pomelo-migration)
- [ ] [Get Recent Mentions](https://discord-userdoccers.vercel.app/resources/user#get-recent-mentions)
- [ ] [Delete Recent Mention](https://discord-userdoccers.vercel.app/resources/user#delete-recent-mention)
- [ ] [Get User Harvest](https://discord-userdoccers.vercel.app/resources/user#get-user-harvest)
- [ ] [Create User Harvest](https://discord-userdoccers.vercel.app/resources/user#create-user-harvest)
- [ ] [Get User Notes](https://discord-userdoccers.vercel.app/resources/user#get-user-notes)
- [ ] [Get User Note](https://discord-userdoccers.vercel.app/resources/user#get-user-note)
- [ ] [Modify User Note](https://discord-userdoccers.vercel.app/resources/user#modify-user-note)
- [ ] [Authorize User Connection](https://discord-userdoccers.vercel.app/resources/user#authorize-user-connection)
- [ ] [Create User Connection Callback](https://discord-userdoccers.vercel.app/resources/user#create-user-connection-callback)
- [ ] [Create User Connection](https://discord-userdoccers.vercel.app/resources/user#create-user-connection)
- [ ] [Get User Connections](https://discord-userdoccers.vercel.app/resources/user#get-user-connections)
- [ ] [Get User Connection Access Token](https://discord-userdoccers.vercel.app/resources/user#get-user-connection-access-token)
- [ ] [Get User Connection Subreddits](https://discord-userdoccers.vercel.app/resources/user#get-user-connection-subreddits)
- [ ] [Refresh User Connection](https://discord-userdoccers.vercel.app/resources/user#refresh-user-connection)
- [ ] [Modify User Connection](https://discord-userdoccers.vercel.app/resources/user#modify-user-connection)
- [ ] [Delete User Connection](https://discord-userdoccers.vercel.app/resources/user#delete-user-connection)
- [ ] [Get User Affinities](https://discord-userdoccers.vercel.app/resources/user#get-user-affinities)
- [ ] [Get Guild Affinities](https://discord-userdoccers.vercel.app/resources/user#get-guild-affinities)
- [ ] [Get User Burst Credits](https://discord-userdoccers.vercel.app/resources/user#get-user-burst-credits)
- [ ] [Get User Premium Usage](https://discord-userdoccers.vercel.app/resources/user#get-user-premium-usage)

**Comment by kozabrada123** [comment]
See the [`user-routes` branch](https://github.com/polyphony-chat/chorus/commits/user-routes/)

**Comment by kozabrada123** [comment]
Most of these routes were added in #537
