### ISSUE TITLE
Auto Moderation

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#222]
- [ ] [Get Guild AutoMod Rules](https://discord-userdoccers.vercel.app/resources/auto-moderation#get-guild-automod-rules)
- [ ] [Get AutoMod Rule](https://discord-userdoccers.vercel.app/resources/auto-moderation#get-automod-rule)
- [ ] [Create AutoMod Rule](https://discord-userdoccers.vercel.app/resources/auto-moderation#create-automod-rule)
- [ ] [Modify AutoMod Rule](https://discord-userdoccers.vercel.app/resources/auto-moderation#modify-automod-rule)
- [ ] [Delete AutoMod Rule](https://discord-userdoccers.vercel.app/resources/auto-moderation#delete-automod-rule)
