### ISSUE TITLE
Channel

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#228]
Some already completed issues have been omitted.

- [ ] [Modify Guild Channel Positions](https://discord-userdoccers.vercel.app/resources/channel#modify-guild-channel-positions)
- [ ] [Delete Read State](https://discord-userdoccers.vercel.app/resources/channel#delete-read-state)
- [ ] [Follow Channel](https://discord-userdoccers.vercel.app/resources/channel#follow-channel)
- [ ] [Trigger Typing Indicator](https://discord-userdoccers.vercel.app/resources/channel#trigger-typing-indicator)
- [ ] [Get Call Eligibility](https://discord-userdoccers.vercel.app/resources/channel#get-call-eligibility)
- [ ] [Modify Call](https://discord-userdoccers.vercel.app/resources/channel#modify-call)
- [ ] [Ring Channel Recipients](https://discord-userdoccers.vercel.app/resources/channel#ring-channel-recipients)
- [ ] [Stop Ringing Channel Recipients](https://discord-userdoccers.vercel.app/resources/channel#stop-ringing-channel-recipients)
- [ ] [Get Guild Active Threads](https://discord-userdoccers.vercel.app/resources/channel#get-guild-active-threads)
- [ ] [Get Active Threads](https://discord-userdoccers.vercel.app/resources/channel#get-active-threads)
- [ ] [Get Public Archived Threads](https://discord-userdoccers.vercel.app/resources/channel#get-public-archived-threads)
- [ ] [Get Private Archived Threads](https://discord-userdoccers.vercel.app/resources/channel#get-private-archived-threads)
- [ ] [Get Joined Private Archived Threads](https://discord-userdoccers.vercel.app/resources/channel#get-joined-private-archived-threads)
- [ ] [Search Threads](https://discord-userdoccers.vercel.app/resources/channel#search-threads)
- [ ] [Create Thread from Message](https://discord-userdoccers.vercel.app/resources/channel#create-thread-from-message)
- [ ] [Create Thread](https://discord-userdoccers.vercel.app/resources/channel#create-thread)
- [ ] [Get Threads Post Data](https://discord-userdoccers.vercel.app/resources/channel#get-threads-post-data)
- [ ] [Get Thread Members](https://discord-userdoccers.vercel.app/resources/channel#get-thread-members)
- [ ] [Get Thread Member](https://discord-userdoccers.vercel.app/resources/channel#get-thread-member)
- [ ] [Join Thread](https://discord-userdoccers.vercel.app/resources/channel#join-thread)
- [ ] [Add Thread Member](https://discord-userdoccers.vercel.app/resources/channel#add-thread-member)
- [ ] [Modify Thread Settings](https://discord-userdoccers.vercel.app/resources/channel#modify-thread-settings)
- [ ] [Leave Thread](https://discord-userdoccers.vercel.app/resources/channel#leave-thread)
- [ ] [Remove Thread Member](https://discord-userdoccers.vercel.app/resources/channel#remove-thread-member)
- [ ] [Create Channel Tag](https://discord-userdoccers.vercel.app/resources/channel#create-channel-tag)
- [ ] [Modify Channel Tag](https://discord-userdoccers.vercel.app/resources/channel#modify-channel-tag)
- [ ] [Delete Channel Tag](https://discord-userdoccers.vercel.app/resources/channel#delete-channel-tag)
