### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#256]
- [ ] [Get Messages](https://discord-userdoccers.vercel.app/resources/message#get-messages)
- [ ] [Search Messages](https://discord-userdoccers.vercel.app/resources/message#search-messages)
- [ ] [Get Message](https://discord-userdoccers.vercel.app/resources/message#get-message)
- [ ] [Create Greet Message](https://discord-userdoccers.vercel.app/resources/message#create-greet-message)
- [ ] [Create Attachments](https://discord-userdoccers.vercel.app/resources/message#create-attachments) (Will eventually supercede the "old" Attachment uploading)
- [ ] [Delete Attachment](https://discord-userdoccers.vercel.app/resources/message#delete-attachment)
- [ ] [Acknowledge Message](https://discord-userdoccers.vercel.app/resources/message#acknowledge-message)
- [ ] [Crosspost Message](https://discord-userdoccers.vercel.app/resources/message#crosspost-message)
- [ ] [Hide Message from Guild Feed](https://discord-userdoccers.vercel.app/resources/message#hide-message-from-guild-feed)
- [ ] [Delete Message](https://discord-userdoccers.vercel.app/resources/message#delete-message)
- [ ] [Bulk Delete Messages](https://discord-userdoccers.vercel.app/resources/message#bulk-delete-messages)
- [ ] [Get Pinned Messages](https://discord-userdoccers.vercel.app/resources/message#get-pinned-messages)
- [ ] [Pin Message](https://discord-userdoccers.vercel.app/resources/message#pin-message)
- [ ] [Unpin Message](https://discord-userdoccers.vercel.app/resources/message#unpin-message)
- [ ] [Acknowledge Pinned Messages](https://discord-userdoccers.vercel.app/resources/message#acknowledge-pinned-messages)
