### ISSUE TITLE
Discovery

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#272]
# Reference

See <https://discord-userdoccers.vercel.app/resources/discovery#endpoints> for an API reference and implementation details.

- [ ] Get Discoverable Guilds
- [ ] Search Discoverable Guilds
- [ ] Get Discovery Slug
- [ ] Get Discovery Categories
- [ ] [Validate Discovery Search Term](https://discord-userdoccers.vercel.app/resources/discovery#validate-discovery-search-term)
- [ ]
