### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#278]
# Reference

See <https://discord-userdoccers.vercel.app/resources/emoji#endpoints> for an API reference and implementation details.

- [ ] [Get Emoji Guild](https://discord-userdoccers.vercel.app/resources/emoji#get-emoji-guild)
- [ ] [Get Guild Emojis](https://discord-userdoccers.vercel.app/resources/emoji#get-guild-emojis)
- [ ] [Get Guild Emoji](https://discord-userdoccers.vercel.app/resources/emoji#get-guild-emoji)
- [ ] [Create Guild Emoji](https://discord-userdoccers.vercel.app/resources/emoji#create-guild-emoji)
- [ ] [Modify Guild Emoji](https://discord-userdoccers.vercel.app/resources/emoji#modify-guild-emoji)
- [ ] [Delete Guild Emoji](https://discord-userdoccers.vercel.app/resources/emoji#delete-guild-emoji)
