### ISSUE TITLE
Guild Scheduled Event

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#323]
# Reference

See <https://discord-userdoccers.vercel.app/resources/discovery#endpoints> for an API reference and implementation details.

- [ ] [Get User Guild Scheduled Events](https://discord-userdoccers.vercel.app/resources/guild-scheduled-event#get-user-guild-scheduled-events)
- [ ] [Get Guild Scheduled Events](https://discord-userdoccers.vercel.app/resources/guild-scheduled-event#get-guild-scheduled-events)
- [ ] [Get Guild Scheduled Event](https://discord-userdoccers.vercel.app/resources/guild-scheduled-event#get-guild-scheduled-event)
- [ ] [Create Guild Scheduled Event](https://discord-userdoccers.vercel.app/resources/guild-scheduled-event#create-guild-scheduled-event)
- [ ] [Modify Guild Scheduled Event](https://discord-userdoccers.vercel.app/resources/guild-scheduled-event#modify-guild-scheduled-event)
- [ ] [Delete Guild Scheduled Event](https://discord-userdoccers.vercel.app/resources/guild-scheduled-event#delete-guild-scheduled-event)
- [ ] [Get Guild Scheduled Event Users](https://discord-userdoccers.vercel.app/resources/guild-scheduled-event#get-guild-scheduled-event-users)
- [ ] [Create Guild Scheduled Event User](https://discord-userdoccers.vercel.app/resources/guild-scheduled-event#create-guild-scheduled-event-user)
- [ ] [Delete Guild Scheduled Event User](https://discord-userdoccers.vercel.app/resources/guild-scheduled-event#delete-guild-scheduled-event-user)
