### ISSUE TITLE
Guild Template

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#333]
# Reference

See <https://discord-userdoccers.vercel.app/resources/guild-template#endpoints> for an API reference and implementation details.

- [ ] [Get Guild Template](https://discord-userdoccers.vercel.app/resources/guild-template#get-guild-template)
- [ ] [Use Guild Template](https://discord-userdoccers.vercel.app/resources/guild-template#use-guild-template)
- [ ] [Get Guild Templates](https://discord-userdoccers.vercel.app/resources/guild-template#get-guild-templates)
- [ ] [Create Guild Template](https://discord-userdoccers.vercel.app/resources/guild-template#create-guild-template)
- [ ] [Sync Guild Template](https://discord-userdoccers.vercel.app/resources/guild-template#sync-guild-template)
- [ ] [Modify Guild Template](https://discord-userdoccers.vercel.app/resources/guild-template#modify-guild-template)
- [ ] [Delete Guild Template](https://discord-userdoccers.vercel.app/resources/guild-template#delete-guild-template)
