### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#341]
# Reference

See <https://discord-userdoccers.vercel.app/resources/integration#endpoints> for an API reference and implementation details.

- [ ] [Get Guild Integrations](https://discord-userdoccers.vercel.app/resources/integration#get-guild-integrations)
- [ ] [Enable Guild Integration](https://discord-userdoccers.vercel.app/resources/integration#enable-guild-integration)
- [ ] [Sync Guild Integration](https://discord-userdoccers.vercel.app/resources/integration#sync-guild-integration)
- [ ] [Modify Guild Integration](https://discord-userdoccers.vercel.app/resources/integration#modify-guild-integration)
- [ ] [Delete Guild Integration](https://discord-userdoccers.vercel.app/resources/integration#delete-guild-integration)
- [ ] [Migrate Guild Command Scope](https://discord-userdoccers.vercel.app/resources/integration#migrate-guild-command-scope)
- [ ] [Modify Channel Integration Consent](https://discord-userdoccers.vercel.app/resources/integration#modify-channel-integration-consent)
- [ ] [Get Channel Integrations](https://discord-userdoccers.vercel.app/resources/integration#get-channel-integrations)
- [ ] [Delete Channel Integration](https://discord-userdoccers.vercel.app/resources/integration#delete-channel-integration)
- [ ] [Get Guild Integration Application IDs](https://discord-userdoccers.vercel.app/resources/integration#get-guild-integration-application-ids)
