### ISSUE TITLE
Invite

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#352]
# Reference

See <https://discord-userdoccers.vercel.app/resources/invite#endpoints> for an API reference and implementation details.

- [ ] [Get Invite](https://discord-userdoccers.vercel.app/resources/invite#get-invite)
- [ ] [Delete Invite](https://discord-userdoccers.vercel.app/resources/invite#delete-invite)
- [ ] [Get Guild Invites](https://discord-userdoccers.vercel.app/resources/invite#get-guild-invites)
- [ ] [Get Channel Invites](https://discord-userdoccers.vercel.app/resources/invite#get-channel-invites)
- [ ] [Create Channel Invite](https://discord-userdoccers.vercel.app/resources/invite#create-channel-invite)
- [ ] [Get User Invites](https://discord-userdoccers.vercel.app/resources/invite#get-user-invites)
- [ ] [Create User Invite](https://discord-userdoccers.vercel.app/resources/invite#create-user-invite)
- [ ] [Revoke User Invites](https://discord-userdoccers.vercel.app/resources/invite#revoke-user-invites)
