### ISSUE TITLE
Premium Referral

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#361]
# Reference

See <https://discord-userdoccers.vercel.app/resources/premium-referral#endpoints> for an API reference and implementation details.

- [ ] [Get Premium Referral](https://discord-userdoccers.vercel.app/resources/premium-referral#get-premium-referral)
- [ ] [Get Premium Referral Eligibility](https://discord-userdoccers.vercel.app/resources/premium-referral#get-premium-referral-eligibility)
- [ ] [Preview Premium Referral](https://discord-userdoccers.vercel.app/resources/premium-referral#preview-premium-referral)
- [ ] [Create Premium Referral](https://discord-userdoccers.vercel.app/resources/premium-referral#create-premium-referral)
