### ISSUE TITLE
Stage Instance

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#368]
# Reference

See <https://discord-userdoccers.vercel.app/resources/stage-instance#endpoints> for an API reference and implementation details.

- [ ] [Get Stage Instance](https://discord-userdoccers.vercel.app/resources/stage-instance#get-stage-instance)
- [ ] [Modify Stage Instance](https://discord-userdoccers.vercel.app/resources/stage-instance#modify-stage-instance)
- [ ] [Delete Stage Instance](https://discord-userdoccers.vercel.app/resources/stage-instance#delete-stage-instance)
