### ISSUE TITLE
Sticker

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#372]
# Reference

See <https://discord-userdoccers.vercel.app/resources/sticker#endpoints> for an API reference and implementation details.

- [ ] [Get Sticker Packs](https://discord-userdoccers.vercel.app/resources/sticker#get-sticker-packs)
- [ ] [Get Sticker Pack](https://discord-userdoccers.vercel.app/resources/sticker#get-sticker-pack)
- [ ] [Get Sticker](https://discord-userdoccers.vercel.app/resources/sticker#get-sticker)
- [ ] [Get Sticker Guild](https://discord-userdoccers.vercel.app/resources/sticker#get-sticker-guild)
- [ ] [Get Guild Stickers](https://discord-userdoccers.vercel.app/resources/sticker#get-guild-stickers)
- [ ] [Get Guild Sticker](https://discord-userdoccers.vercel.app/resources/sticker#get-guild-sticker)
- [ ] [Create Guild Sticker](https://discord-userdoccers.vercel.app/resources/sticker#create-guild-sticker)
- [ ] [Modify Guild Sticker](https://discord-userdoccers.vercel.app/resources/sticker#modify-guild-sticker)
- [ ] [Delete Guild Sticker](https://discord-userdoccers.vercel.app/resources/sticker#delete-guild-sticker)
