### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#382]
# Reference

See <https://discord-userdoccers.vercel.app/resources/webhook> for an API reference and implementation details.

- [ ] [Create Webhook](https://discord-userdoccers.vercel.app/resources/webhook#create-webhook)
- [ ] [Get Channel Webhooks](https://discord-userdoccers.vercel.app/resources/webhook#get-channel-webhooks)
- [ ] [Get Guild Webhooks](https://discord-userdoccers.vercel.app/resources/webhook#get-guild-webhooks)
- [ ] [Get Webhook](https://discord-userdoccers.vercel.app/resources/webhook#get-webhook)
- [ ] [Get Webhook with Token](https://discord-userdoccers.vercel.app/resources/webhook#get-webhook-with-token)
- [ ] [Modify Webhook](https://discord-userdoccers.vercel.app/resources/webhook#modify-webhook)
- [ ] [Modify Webhook with Token](https://discord-userdoccers.vercel.app/resources/webhook#modify-webhook-with-token)
- [ ] [Delete Webhook](https://discord-userdoccers.vercel.app/resources/webhook#delete-webhook)
- [ ] [Delete Webhook with Token](https://discord-userdoccers.vercel.app/resources/webhook#delete-webhook-with-token)
- [ ] [Execute Webhook](https://discord-userdoccers.vercel.app/resources/webhook#execute-webhook)
- [ ] [Execute Slack-Compatible Webhook](https://discord-userdoccers.vercel.app/resources/webhook#execute-slack-compatible-webhook)
- [ ] [Execute GitHub-Compatible Webhook](https://discord-userdoccers.vercel.app/resources/webhook#execute-github-compatible-webhook)
- [ ] [Get Webhook Message](https://discord-userdoccers.vercel.app/resources/webhook#get-webhook-message)
- [ ] [Edit Webhook Message](https://discord-userdoccers.vercel.app/resources/webhook#edit-webhook-message)
- [ ] [Delete Webhook Message](https://discord-userdoccers.vercel.app/resources/webhook#delete-webhook-message)
