### ISSUE TITLE
polyproto in chorus: Tracking issue

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/chorus#517]
polyproto is a new protocol for identity federation and federated message exchange. It was conceptualized to become a bespoke federation solution for polyphony and as such, should eventually be integrated into our core software (symfonia and chorus). This is an organizational/tracking issue for things that need to be done on the chorus-side of things to achieve this. This list will be edited in the future, as more tasks get added and others get completed.

To disambiguate some of the terminology mentioned in this issue:

**polyphony**: Our federated chat service. A subset of some of the functionality offered by spacebarchat, excluding things like super reactions, profile decorations, et cetera. Uses the polyproto protocol to federate.
**chorus**: A spacebarchat *and* polyphony compatible API wrapping library. Must be spacebar compatible to act as an adapter/translator between polyphony and spacebarchat, for features that the one implementation has but the other one lacks. Must be polyphony compatible to, well, power polyphony-related software.
**polyproto**: A federation protocol.
**spacebar(chat)**: A 1:1 API compatible, open-source re-implementation of the Discord server.

## Tasks

polyproto support should be feature-locked. Here are some of the core to-dos:

### polyproto-core

- [ ] Integrate polyproto login into chorus: Create `ChorusUser` by signing in with polyproto

### polyproto-chat

These tasks are likely blocked, as the polyproto-chat polyproto extension is not yet defined.

- [ ] Validate signatures of all received P2 messages
- [ ] Generate signatures when sending messages
